### ISSUE TITLE
Fila Shield mounting?

### ISSUE THREAD

**Issue by rufinus** [probably-Erwins-Cat/ERCF-Buffer-Array#3]
How did you mount the Fila Shield to the connector? 

I see on the bottom of the filashield the two shields are connected with a string of filament. 
But i cant see what you use on top where its sits on the arm. is this a rivet?

Do you find the Shield is needed in general or optional? (will be used in a 9er ercf)

tia
Ludwig

**Comment by probably-Erwins-Cat** [comment]
The fila shields have special connectors that clip into the buffer crosses and contain the standard 6x3 magnets from Voron design philosophy. The connectors then hold the film shields in place via the magnets. This makes adding and removing the shields easier when refilling the buffer with new filament.

**Comment by rufinus** [comment]
ah magnets, thank you. thats a lot of magnets :)
